// Code generated by goctl. DO NOT EDIT.
// Source: sys.proto

package server

import (
	"context"

	"gitee.com/i-Things/core/service/syssvr/internal/logic/common"
	"gitee.com/i-Things/core/service/syssvr/internal/svc"
	"gitee.com/i-Things/core/service/syssvr/pb/sys"
)

type CommonServer struct {
	svcCtx *svc.ServiceContext
	sys.UnimplementedCommonServer
}

func NewCommonServer(svcCtx *svc.ServiceContext) *CommonServer {
	return &CommonServer{
		svcCtx: svcCtx,
	}
}

func (s *CommonServer) Config(ctx context.Context, in *sys.Empty) (*sys.ConfigResp, error) {
	l := commonlogic.NewConfigLogic(ctx, s.svcCtx)
	return l.Config(in)
}

func (s *CommonServer) SlotInfoIndex(ctx context.Context, in *sys.SlotInfoIndexReq) (*sys.SlotInfoIndexResp, error) {
	l := commonlogic.NewSlotInfoIndexLogic(ctx, s.svcCtx)
	return l.SlotInfoIndex(in)
}

func (s *CommonServer) QRCodeRead(ctx context.Context, in *sys.QRCodeReadReq) (*sys.QRCodeReadResp, error) {
	l := commonlogic.NewQRCodeReadLogic(ctx, s.svcCtx)
	return l.QRCodeRead(in)
}
