// TemplateCode generated by goctl. DO NOT EDIT.
// Source: sys.proto

package server

import (
	"context"

	"gitee.com/i-Things/core/service/syssvr/internal/logic/messagemanage"
	"gitee.com/i-Things/core/service/syssvr/internal/svc"
	"gitee.com/i-Things/core/service/syssvr/pb/sys"
)

type MessageManageServer struct {
	svcCtx *svc.ServiceContext
	sys.UnimplementedMessageManageServer
}

func NewMessageManageServer(svcCtx *svc.ServiceContext) *MessageManageServer {
	return &MessageManageServer{
		svcCtx: svcCtx,
	}
}

func (s *MessageManageServer) Ping(ctx context.Context, in *sys.Response) (*sys.Response, error) {
	l := messagemanagelogic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
