// Code generated by goctl. DO NOT EDIT.
package types

type StaticsticsInfoReadReq struct {
	Code      string                 `json:"code"`
	Filter    map[string]interface{} `json:"filter,optional"`
	ArgFunc   string                 `json:"argFunc,optional"` //聚合函数
	GroupBy   string                 `json:"groupBy,optional"`
	ArgColumn string                 `json:"argColumn,optional"` //聚合的列,逗号分隔
	Columns   string                 `json:"columns,optional"`
}

type StaticsticsInfoReadResp struct {
	List []map[string]interface{} `json:"list"`
}
