// Code generated by goctl. DO NOT EDIT.
package types

type Aggregation struct {
	Func   string `json:"argFunc,optional"`
	Column string `json:"column,optional"`
}

type StaticsticsInfoReadReq struct {
	Code         string                 `json:"code"`
	Filter       map[string]interface{} `json:"filter,optional"`
	Aggregations []Aggregation          `json:"aggregations,optional"`
	GroupBy      string                 `json:"groupBy,optional"`
	Columns      string                 `json:"columns,optional"`
}

type StaticsticsInfoReadResp struct {
	List []map[string]interface{} `json:"list"` //如果返回的是个列表
	One  interface{}              `json:"one"`  //如果只返回一个数
}
