// Code generated by goctl. DO NOT EDIT.
package types

type Aggregation struct {
	Func   string `json:"argFunc,optional"`
	Column string `json:"column,optional"`
}

type Column struct {
	Column   string `json:"column"`   //导出的列
	ShowName string `json:"showName"` //展示的名字
}

type OrderBy struct {
	Field string `json:"field,optional"` ////排序的字段名
	Sort  int64  `json:"sort,optional"`  //排序方式：0 从小到大, 1 从大到小
}

type PageInfo struct {
	Page   int64      `json:"page,optional" form:"page,optional"` // 页码
	Size   int64      `json:"size,optional" form:"size,optional"` // 每页大小
	Orders []*OrderBy `json:"orders,optional"`                    //排序
}

type StaticsticsInfoExportReq struct {
	Columns []Column `json:"columns"`
	Format  string   `json:"format"` //默认xslx
}

type StaticsticsInfoIndexReq struct {
	Finds []*StaticsticsInfoReadReq `json:"finds"`
}

type StaticsticsInfoIndexResp struct {
	Lists [][]map[string]interface{} `json:"list"`
}

type StaticsticsInfoReadReq struct {
	Code         string                 `json:"code"`
	IsAllProject bool                   `json:"isAllProject,optional"` //获取全部项目的数据
	Page         *PageInfo              `json:"page,optional"`
	Filter       map[string]interface{} `json:"filter,optional"`
	Aggregations []Aggregation          `json:"aggregations,optional"`
	GroupBy      string                 `json:"groupBy,optional"`
	Columns      string                 `json:"columns,optional"`
}

type StaticsticsInfoReadResp struct {
	List []map[string]interface{} `json:"list"` //如果返回的是个列表
	One  interface{}              `json:"one"`  //如果只返回一个数
}
