// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.1
// Source: sys.proto

package server

import (
	"context"

	"gitee.com/unitedrhino/core/service/syssvr/internal/logic/dictmanage"
	"gitee.com/unitedrhino/core/service/syssvr/internal/svc"
	"gitee.com/unitedrhino/core/service/syssvr/pb/sys"
)

type DictManageServer struct {
	svcCtx *svc.ServiceContext
	sys.UnimplementedDictManageServer
}

func NewDictManageServer(svcCtx *svc.ServiceContext) *DictManageServer {
	return &DictManageServer{
		svcCtx: svcCtx,
	}
}

func (s *DictManageServer) DictInfoCreate(ctx context.Context, in *sys.DictInfo) (*sys.WithID, error) {
	l := dictmanagelogic.NewDictInfoCreateLogic(ctx, s.svcCtx)
	return l.DictInfoCreate(in)
}

func (s *DictManageServer) DictInfoIndex(ctx context.Context, in *sys.DictInfoIndexReq) (*sys.DictInfoIndexResp, error) {
	l := dictmanagelogic.NewDictInfoIndexLogic(ctx, s.svcCtx)
	return l.DictInfoIndex(in)
}

func (s *DictManageServer) DictInfoUpdate(ctx context.Context, in *sys.DictInfo) (*sys.Empty, error) {
	l := dictmanagelogic.NewDictInfoUpdateLogic(ctx, s.svcCtx)
	return l.DictInfoUpdate(in)
}

func (s *DictManageServer) DictInfoDelete(ctx context.Context, in *sys.WithID) (*sys.Empty, error) {
	l := dictmanagelogic.NewDictInfoDeleteLogic(ctx, s.svcCtx)
	return l.DictInfoDelete(in)
}

func (s *DictManageServer) DictInfoRead(ctx context.Context, in *sys.DictInfoReadReq) (*sys.DictInfo, error) {
	l := dictmanagelogic.NewDictInfoReadLogic(ctx, s.svcCtx)
	return l.DictInfoRead(in)
}

func (s *DictManageServer) DictDetailRead(ctx context.Context, in *sys.DictDetailReadReq) (*sys.DictDetail, error) {
	l := dictmanagelogic.NewDictDetailReadLogic(ctx, s.svcCtx)
	return l.DictDetailRead(in)
}

func (s *DictManageServer) DictDetailCreate(ctx context.Context, in *sys.DictDetail) (*sys.WithID, error) {
	l := dictmanagelogic.NewDictDetailCreateLogic(ctx, s.svcCtx)
	return l.DictDetailCreate(in)
}

func (s *DictManageServer) DictDetailMultiCreate(ctx context.Context, in *sys.DictDetailMultiCreateReq) (*sys.Empty, error) {
	l := dictmanagelogic.NewDictDetailMultiCreateLogic(ctx, s.svcCtx)
	return l.DictDetailMultiCreate(in)
}

func (s *DictManageServer) DictDetailIndex(ctx context.Context, in *sys.DictDetailIndexReq) (*sys.DictDetailIndexResp, error) {
	l := dictmanagelogic.NewDictDetailIndexLogic(ctx, s.svcCtx)
	return l.DictDetailIndex(in)
}

func (s *DictManageServer) DictDetailUpdate(ctx context.Context, in *sys.DictDetail) (*sys.Empty, error) {
	l := dictmanagelogic.NewDictDetailUpdateLogic(ctx, s.svcCtx)
	return l.DictDetailUpdate(in)
}

func (s *DictManageServer) DictDetailDelete(ctx context.Context, in *sys.WithID) (*sys.Empty, error) {
	l := dictmanagelogic.NewDictDetailDeleteLogic(ctx, s.svcCtx)
	return l.DictDetailDelete(in)
}

func (s *DictManageServer) DictMultiImport(ctx context.Context, in *sys.DictMultiImportReq) (*sys.DictMultiImportResp, error) {
	l := dictmanagelogic.NewDictMultiImportLogic(ctx, s.svcCtx)
	return l.DictMultiImport(in)
}

func (s *DictManageServer) DictMultiExport(ctx context.Context, in *sys.DictMultiExportReq) (*sys.DictMultiExportResp, error) {
	l := dictmanagelogic.NewDictMultiExportLogic(ctx, s.svcCtx)
	return l.DictMultiExport(in)
}
