// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	datastaticsticsinfo "gitee.com/i-Things/core/service/datasvr/internal/handler/data/staticstics/info"
	"gitee.com/i-Things/core/service/datasvr/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.CheckTokenWare, serverCtx.InitCtxsWare},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/read",
					Handler: datastaticsticsinfo.ReadHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1/data/staticstics/info"),
	)
}
