// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.1
// Source: sys.proto

package notifymanage

import (
	"context"

	"gitee.com/unitedrhino/core/service/syssvr/internal/svc"
	"gitee.com/unitedrhino/core/service/syssvr/pb/sys"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AccessInfo                            = sys.AccessInfo
	AccessInfoIndexReq                    = sys.AccessInfoIndexReq
	AccessInfoIndexResp                   = sys.AccessInfoIndexResp
	AccessInfoMultiImportReq              = sys.AccessInfoMultiImportReq
	AccessInfoMultiImportResp             = sys.AccessInfoMultiImportResp
	ApiInfo                               = sys.ApiInfo
	ApiInfoIndexReq                       = sys.ApiInfoIndexReq
	ApiInfoIndexResp                      = sys.ApiInfoIndexResp
	AppInfo                               = sys.AppInfo
	AppInfoIndexReq                       = sys.AppInfoIndexReq
	AppInfoIndexResp                      = sys.AppInfoIndexResp
	AppModuleIndexReq                     = sys.AppModuleIndexReq
	AppModuleIndexResp                    = sys.AppModuleIndexResp
	AppModuleMultiUpdateReq               = sys.AppModuleMultiUpdateReq
	AreaInfo                              = sys.AreaInfo
	AreaInfoIndexReq                      = sys.AreaInfoIndexReq
	AreaInfoIndexResp                     = sys.AreaInfoIndexResp
	AreaInfoReadReq                       = sys.AreaInfoReadReq
	AreaProfile                           = sys.AreaProfile
	AreaProfileIndexReq                   = sys.AreaProfileIndexReq
	AreaProfileIndexResp                  = sys.AreaProfileIndexResp
	AreaProfileReadReq                    = sys.AreaProfileReadReq
	AreaWithID                            = sys.AreaWithID
	AuthApiInfo                           = sys.AuthApiInfo
	CompareInt64                          = sys.CompareInt64
	CompareString                         = sys.CompareString
	ConfigResp                            = sys.ConfigResp
	DataArea                              = sys.DataArea
	DataAreaIndexReq                      = sys.DataAreaIndexReq
	DataAreaIndexResp                     = sys.DataAreaIndexResp
	DataAreaMultiDeleteReq                = sys.DataAreaMultiDeleteReq
	DataAreaMultiUpdateReq                = sys.DataAreaMultiUpdateReq
	DataProject                           = sys.DataProject
	DataProjectDeleteReq                  = sys.DataProjectDeleteReq
	DataProjectIndexReq                   = sys.DataProjectIndexReq
	DataProjectIndexResp                  = sys.DataProjectIndexResp
	DataProjectMultiDeleteReq             = sys.DataProjectMultiDeleteReq
	DataProjectMultiSaveReq               = sys.DataProjectMultiSaveReq
	DataProjectSaveReq                    = sys.DataProjectSaveReq
	DateRange                             = sys.DateRange
	DeptInfo                              = sys.DeptInfo
	DeptInfoIndexReq                      = sys.DeptInfoIndexReq
	DeptInfoIndexResp                     = sys.DeptInfoIndexResp
	DeptInfoReadReq                       = sys.DeptInfoReadReq
	DeptInfoSyncReq                       = sys.DeptInfoSyncReq
	DeptInfoSyncResp                      = sys.DeptInfoSyncResp
	DeptRoleIndexReq                      = sys.DeptRoleIndexReq
	DeptRoleIndexResp                     = sys.DeptRoleIndexResp
	DeptRoleMultiSaveReq                  = sys.DeptRoleMultiSaveReq
	DeptUserIndexReq                      = sys.DeptUserIndexReq
	DeptUserIndexResp                     = sys.DeptUserIndexResp
	DeptUserMultiSaveReq                  = sys.DeptUserMultiSaveReq
	DictDetail                            = sys.DictDetail
	DictDetailIndexReq                    = sys.DictDetailIndexReq
	DictDetailIndexResp                   = sys.DictDetailIndexResp
	DictDetailReadReq                     = sys.DictDetailReadReq
	DictInfo                              = sys.DictInfo
	DictInfoIndexReq                      = sys.DictInfoIndexReq
	DictInfoIndexResp                     = sys.DictInfoIndexResp
	DictInfoReadReq                       = sys.DictInfoReadReq
	Empty                                 = sys.Empty
	IDList                                = sys.IDList
	JwtToken                              = sys.JwtToken
	LoginLogCreateReq                     = sys.LoginLogCreateReq
	LoginLogIndexReq                      = sys.LoginLogIndexReq
	LoginLogIndexResp                     = sys.LoginLogIndexResp
	LoginLogInfo                          = sys.LoginLogInfo
	Map                                   = sys.Map
	MenuInfo                              = sys.MenuInfo
	MenuInfoIndexReq                      = sys.MenuInfoIndexReq
	MenuInfoIndexResp                     = sys.MenuInfoIndexResp
	MenuMultiExportReq                    = sys.MenuMultiExportReq
	MenuMultiExportResp                   = sys.MenuMultiExportResp
	MenuMultiImportReq                    = sys.MenuMultiImportReq
	MenuMultiImportResp                   = sys.MenuMultiImportResp
	MessageInfo                           = sys.MessageInfo
	MessageInfoIndexReq                   = sys.MessageInfoIndexReq
	MessageInfoIndexResp                  = sys.MessageInfoIndexResp
	MessageInfoSendReq                    = sys.MessageInfoSendReq
	ModuleInfo                            = sys.ModuleInfo
	ModuleInfoIndexReq                    = sys.ModuleInfoIndexReq
	ModuleInfoIndexResp                   = sys.ModuleInfoIndexResp
	NotifyChannel                         = sys.NotifyChannel
	NotifyChannelIndexReq                 = sys.NotifyChannelIndexReq
	NotifyChannelIndexResp                = sys.NotifyChannelIndexResp
	NotifyConfig                          = sys.NotifyConfig
	NotifyConfigIndexReq                  = sys.NotifyConfigIndexReq
	NotifyConfigIndexResp                 = sys.NotifyConfigIndexResp
	NotifyConfigSendReq                   = sys.NotifyConfigSendReq
	NotifyConfigTemplate                  = sys.NotifyConfigTemplate
	NotifyConfigTemplateDeleteReq         = sys.NotifyConfigTemplateDeleteReq
	NotifyConfigTemplateIndexReq          = sys.NotifyConfigTemplateIndexReq
	NotifyConfigTemplateIndexResp         = sys.NotifyConfigTemplateIndexResp
	NotifyTemplate                        = sys.NotifyTemplate
	NotifyTemplateIndexReq                = sys.NotifyTemplateIndexReq
	NotifyTemplateIndexResp               = sys.NotifyTemplateIndexResp
	OpenAccess                            = sys.OpenAccess
	OpenAccessIndexReq                    = sys.OpenAccessIndexReq
	OpenAccessIndexResp                   = sys.OpenAccessIndexResp
	OperLogCreateReq                      = sys.OperLogCreateReq
	OperLogIndexReq                       = sys.OperLogIndexReq
	OperLogIndexResp                      = sys.OperLogIndexResp
	OperLogInfo                           = sys.OperLogInfo
	OpsFeedback                           = sys.OpsFeedback
	OpsFeedbackIndexReq                   = sys.OpsFeedbackIndexReq
	OpsFeedbackIndexResp                  = sys.OpsFeedbackIndexResp
	OpsWorkOrder                          = sys.OpsWorkOrder
	OpsWorkOrderIndexReq                  = sys.OpsWorkOrderIndexReq
	OpsWorkOrderIndexResp                 = sys.OpsWorkOrderIndexResp
	PageInfo                              = sys.PageInfo
	PageInfo_OrderBy                      = sys.PageInfo_OrderBy
	Point                                 = sys.Point
	ProjectAuth                           = sys.ProjectAuth
	ProjectInfo                           = sys.ProjectInfo
	ProjectInfoIndexReq                   = sys.ProjectInfoIndexReq
	ProjectInfoIndexResp                  = sys.ProjectInfoIndexResp
	ProjectProfile                        = sys.ProjectProfile
	ProjectProfileIndexReq                = sys.ProjectProfileIndexReq
	ProjectProfileIndexResp               = sys.ProjectProfileIndexResp
	ProjectProfileReadReq                 = sys.ProjectProfileReadReq
	ProjectWithID                         = sys.ProjectWithID
	QRCodeReadReq                         = sys.QRCodeReadReq
	QRCodeReadResp                        = sys.QRCodeReadResp
	RoleAccessIndexReq                    = sys.RoleAccessIndexReq
	RoleAccessIndexResp                   = sys.RoleAccessIndexResp
	RoleAccessMultiUpdateReq              = sys.RoleAccessMultiUpdateReq
	RoleApiAuthReq                        = sys.RoleApiAuthReq
	RoleApiAuthResp                       = sys.RoleApiAuthResp
	RoleAppIndexReq                       = sys.RoleAppIndexReq
	RoleAppIndexResp                      = sys.RoleAppIndexResp
	RoleAppMultiUpdateReq                 = sys.RoleAppMultiUpdateReq
	RoleAppUpdateReq                      = sys.RoleAppUpdateReq
	RoleInfo                              = sys.RoleInfo
	RoleInfoIndexReq                      = sys.RoleInfoIndexReq
	RoleInfoIndexResp                     = sys.RoleInfoIndexResp
	RoleMenuIndexReq                      = sys.RoleMenuIndexReq
	RoleMenuIndexResp                     = sys.RoleMenuIndexResp
	RoleMenuMultiUpdateReq                = sys.RoleMenuMultiUpdateReq
	RoleModuleIndexReq                    = sys.RoleModuleIndexReq
	RoleModuleIndexResp                   = sys.RoleModuleIndexResp
	RoleModuleMultiUpdateReq              = sys.RoleModuleMultiUpdateReq
	SendOption                            = sys.SendOption
	ServiceInfo                           = sys.ServiceInfo
	SlotInfo                              = sys.SlotInfo
	SlotInfoIndexReq                      = sys.SlotInfoIndexReq
	SlotInfoIndexResp                     = sys.SlotInfoIndexResp
	TenantAccessIndexReq                  = sys.TenantAccessIndexReq
	TenantAccessIndexResp                 = sys.TenantAccessIndexResp
	TenantAccessMultiSaveReq              = sys.TenantAccessMultiSaveReq
	TenantAgreement                       = sys.TenantAgreement
	TenantAgreementIndexReq               = sys.TenantAgreementIndexReq
	TenantAgreementIndexResp              = sys.TenantAgreementIndexResp
	TenantAppIndexReq                     = sys.TenantAppIndexReq
	TenantAppIndexResp                    = sys.TenantAppIndexResp
	TenantAppInfo                         = sys.TenantAppInfo
	TenantAppMenu                         = sys.TenantAppMenu
	TenantAppMenuIndexReq                 = sys.TenantAppMenuIndexReq
	TenantAppMenuIndexResp                = sys.TenantAppMenuIndexResp
	TenantAppModule                       = sys.TenantAppModule
	TenantAppMultiUpdateReq               = sys.TenantAppMultiUpdateReq
	TenantAppWithIDOrCode                 = sys.TenantAppWithIDOrCode
	TenantConfig                          = sys.TenantConfig
	TenantConfigRegisterAutoCreateArea    = sys.TenantConfigRegisterAutoCreateArea
	TenantConfigRegisterAutoCreateProject = sys.TenantConfigRegisterAutoCreateProject
	TenantInfo                            = sys.TenantInfo
	TenantInfoCreateReq                   = sys.TenantInfoCreateReq
	TenantInfoIndexReq                    = sys.TenantInfoIndexReq
	TenantInfoIndexResp                   = sys.TenantInfoIndexResp
	TenantModuleCreateReq                 = sys.TenantModuleCreateReq
	TenantModuleIndexReq                  = sys.TenantModuleIndexReq
	TenantModuleIndexResp                 = sys.TenantModuleIndexResp
	TenantModuleWithIDOrCode              = sys.TenantModuleWithIDOrCode
	TenantOpenCheckTokenReq               = sys.TenantOpenCheckTokenReq
	TenantOpenCheckTokenResp              = sys.TenantOpenCheckTokenResp
	TenantOpenWebHook                     = sys.TenantOpenWebHook
	ThirdApp                              = sys.ThirdApp
	ThirdAppConfig                        = sys.ThirdAppConfig
	ThirdEmail                            = sys.ThirdEmail
	ThirdSms                              = sys.ThirdSms
	UserAreaApplyCreateReq                = sys.UserAreaApplyCreateReq
	UserAreaApplyDealReq                  = sys.UserAreaApplyDealReq
	UserAreaApplyIndexReq                 = sys.UserAreaApplyIndexReq
	UserAreaApplyIndexResp                = sys.UserAreaApplyIndexResp
	UserAreaApplyInfo                     = sys.UserAreaApplyInfo
	UserBindAccountReq                    = sys.UserBindAccountReq
	UserCaptchaReq                        = sys.UserCaptchaReq
	UserCaptchaResp                       = sys.UserCaptchaResp
	UserChangePwdReq                      = sys.UserChangePwdReq
	UserCheckTokenReq                     = sys.UserCheckTokenReq
	UserCheckTokenResp                    = sys.UserCheckTokenResp
	UserCodeToUserIDReq                   = sys.UserCodeToUserIDReq
	UserCodeToUserIDResp                  = sys.UserCodeToUserIDResp
	UserCreateResp                        = sys.UserCreateResp
	UserDeptIndexReq                      = sys.UserDeptIndexReq
	UserDeptIndexResp                     = sys.UserDeptIndexResp
	UserDeptMultiSaveReq                  = sys.UserDeptMultiSaveReq
	UserForgetPwdReq                      = sys.UserForgetPwdReq
	UserInfo                              = sys.UserInfo
	UserInfoCreateReq                     = sys.UserInfoCreateReq
	UserInfoDeleteReq                     = sys.UserInfoDeleteReq
	UserInfoIndexReq                      = sys.UserInfoIndexReq
	UserInfoIndexResp                     = sys.UserInfoIndexResp
	UserInfoReadReq                       = sys.UserInfoReadReq
	UserInfoUpdateReq                     = sys.UserInfoUpdateReq
	UserLoginReq                          = sys.UserLoginReq
	UserLoginResp                         = sys.UserLoginResp
	UserMessage                           = sys.UserMessage
	UserMessageIndexReq                   = sys.UserMessageIndexReq
	UserMessageIndexResp                  = sys.UserMessageIndexResp
	UserMessageStatistics                 = sys.UserMessageStatistics
	UserMessageStatisticsResp             = sys.UserMessageStatisticsResp
	UserProfile                           = sys.UserProfile
	UserProfileIndexReq                   = sys.UserProfileIndexReq
	UserProfileIndexResp                  = sys.UserProfileIndexResp
	UserRegisterReq                       = sys.UserRegisterReq
	UserRegisterResp                      = sys.UserRegisterResp
	UserRoleIndexReq                      = sys.UserRoleIndexReq
	UserRoleIndexResp                     = sys.UserRoleIndexResp
	UserRoleMultiUpdateReq                = sys.UserRoleMultiUpdateReq
	WeatherAir                            = sys.WeatherAir
	WeatherReadReq                        = sys.WeatherReadReq
	WeatherReadResp                       = sys.WeatherReadResp
	WithAppCodeID                         = sys.WithAppCodeID
	WithCode                              = sys.WithCode
	WithID                                = sys.WithID
	WithIDCode                            = sys.WithIDCode

	NotifyManage interface {
		// 站内信
		MessageInfoSend(ctx context.Context, in *MessageInfoSendReq, opts ...grpc.CallOption) (*WithID, error)
		MessageInfoIndex(ctx context.Context, in *MessageInfoIndexReq, opts ...grpc.CallOption) (*MessageInfoIndexResp, error)
		MessageInfoUpdate(ctx context.Context, in *MessageInfo, opts ...grpc.CallOption) (*Empty, error)
		MessageInfoDelete(ctx context.Context, in *WithID, opts ...grpc.CallOption) (*Empty, error)
		// 通知配置信息
		NotifyConfigRead(ctx context.Context, in *WithIDCode, opts ...grpc.CallOption) (*NotifyConfig, error)
		NotifyConfigCreate(ctx context.Context, in *NotifyConfig, opts ...grpc.CallOption) (*WithID, error)
		NotifyConfigUpdate(ctx context.Context, in *NotifyConfig, opts ...grpc.CallOption) (*Empty, error)
		NotifyConfigIndex(ctx context.Context, in *NotifyConfigIndexReq, opts ...grpc.CallOption) (*NotifyConfigIndexResp, error)
		NotifyConfigDelete(ctx context.Context, in *WithID, opts ...grpc.CallOption) (*Empty, error)
		NotifyConfigSend(ctx context.Context, in *NotifyConfigSendReq, opts ...grpc.CallOption) (*Empty, error)
		// 通知模版
		NotifyTemplateRead(ctx context.Context, in *WithID, opts ...grpc.CallOption) (*NotifyTemplate, error)
		NotifyTemplateCreate(ctx context.Context, in *NotifyTemplate, opts ...grpc.CallOption) (*WithID, error)
		NotifyTemplateUpdate(ctx context.Context, in *NotifyTemplate, opts ...grpc.CallOption) (*Empty, error)
		NotifyTemplateIndex(ctx context.Context, in *NotifyTemplateIndexReq, opts ...grpc.CallOption) (*NotifyTemplateIndexResp, error)
		NotifyTemplateDelete(ctx context.Context, in *WithID, opts ...grpc.CallOption) (*Empty, error)
		// 租户通知配置
		NotifyConfigTemplateUpdate(ctx context.Context, in *NotifyConfigTemplate, opts ...grpc.CallOption) (*Empty, error)
		NotifyConfigTemplateDelete(ctx context.Context, in *NotifyConfigTemplateDeleteReq, opts ...grpc.CallOption) (*Empty, error)
		NotifyConfigTemplateIndex(ctx context.Context, in *NotifyConfigTemplateIndexReq, opts ...grpc.CallOption) (*NotifyConfigTemplateIndexResp, error)
		NotifyChannelRead(ctx context.Context, in *WithID, opts ...grpc.CallOption) (*NotifyChannel, error)
		NotifyChannelCreate(ctx context.Context, in *NotifyChannel, opts ...grpc.CallOption) (*WithID, error)
		NotifyChannelUpdate(ctx context.Context, in *NotifyChannel, opts ...grpc.CallOption) (*Empty, error)
		NotifyChannelIndex(ctx context.Context, in *NotifyChannelIndexReq, opts ...grpc.CallOption) (*NotifyChannelIndexResp, error)
		NotifyChannelDelete(ctx context.Context, in *WithID, opts ...grpc.CallOption) (*Empty, error)
	}

	defaultNotifyManage struct {
		cli zrpc.Client
	}

	directNotifyManage struct {
		svcCtx *svc.ServiceContext
		svr    sys.NotifyManageServer
	}
)

func NewNotifyManage(cli zrpc.Client) NotifyManage {
	return &defaultNotifyManage{
		cli: cli,
	}
}

func NewDirectNotifyManage(svcCtx *svc.ServiceContext, svr sys.NotifyManageServer) NotifyManage {
	return &directNotifyManage{
		svr:    svr,
		svcCtx: svcCtx,
	}
}

// 站内信
func (m *defaultNotifyManage) MessageInfoSend(ctx context.Context, in *MessageInfoSendReq, opts ...grpc.CallOption) (*WithID, error) {
	client := sys.NewNotifyManageClient(m.cli.Conn())
	return client.MessageInfoSend(ctx, in, opts...)
}

// 站内信
func (d *directNotifyManage) MessageInfoSend(ctx context.Context, in *MessageInfoSendReq, opts ...grpc.CallOption) (*WithID, error) {
	return d.svr.MessageInfoSend(ctx, in)
}

func (m *defaultNotifyManage) MessageInfoIndex(ctx context.Context, in *MessageInfoIndexReq, opts ...grpc.CallOption) (*MessageInfoIndexResp, error) {
	client := sys.NewNotifyManageClient(m.cli.Conn())
	return client.MessageInfoIndex(ctx, in, opts...)
}

func (d *directNotifyManage) MessageInfoIndex(ctx context.Context, in *MessageInfoIndexReq, opts ...grpc.CallOption) (*MessageInfoIndexResp, error) {
	return d.svr.MessageInfoIndex(ctx, in)
}

func (m *defaultNotifyManage) MessageInfoUpdate(ctx context.Context, in *MessageInfo, opts ...grpc.CallOption) (*Empty, error) {
	client := sys.NewNotifyManageClient(m.cli.Conn())
	return client.MessageInfoUpdate(ctx, in, opts...)
}

func (d *directNotifyManage) MessageInfoUpdate(ctx context.Context, in *MessageInfo, opts ...grpc.CallOption) (*Empty, error) {
	return d.svr.MessageInfoUpdate(ctx, in)
}

func (m *defaultNotifyManage) MessageInfoDelete(ctx context.Context, in *WithID, opts ...grpc.CallOption) (*Empty, error) {
	client := sys.NewNotifyManageClient(m.cli.Conn())
	return client.MessageInfoDelete(ctx, in, opts...)
}

func (d *directNotifyManage) MessageInfoDelete(ctx context.Context, in *WithID, opts ...grpc.CallOption) (*Empty, error) {
	return d.svr.MessageInfoDelete(ctx, in)
}

// 通知配置信息
func (m *defaultNotifyManage) NotifyConfigRead(ctx context.Context, in *WithIDCode, opts ...grpc.CallOption) (*NotifyConfig, error) {
	client := sys.NewNotifyManageClient(m.cli.Conn())
	return client.NotifyConfigRead(ctx, in, opts...)
}

// 通知配置信息
func (d *directNotifyManage) NotifyConfigRead(ctx context.Context, in *WithIDCode, opts ...grpc.CallOption) (*NotifyConfig, error) {
	return d.svr.NotifyConfigRead(ctx, in)
}

func (m *defaultNotifyManage) NotifyConfigCreate(ctx context.Context, in *NotifyConfig, opts ...grpc.CallOption) (*WithID, error) {
	client := sys.NewNotifyManageClient(m.cli.Conn())
	return client.NotifyConfigCreate(ctx, in, opts...)
}

func (d *directNotifyManage) NotifyConfigCreate(ctx context.Context, in *NotifyConfig, opts ...grpc.CallOption) (*WithID, error) {
	return d.svr.NotifyConfigCreate(ctx, in)
}

func (m *defaultNotifyManage) NotifyConfigUpdate(ctx context.Context, in *NotifyConfig, opts ...grpc.CallOption) (*Empty, error) {
	client := sys.NewNotifyManageClient(m.cli.Conn())
	return client.NotifyConfigUpdate(ctx, in, opts...)
}

func (d *directNotifyManage) NotifyConfigUpdate(ctx context.Context, in *NotifyConfig, opts ...grpc.CallOption) (*Empty, error) {
	return d.svr.NotifyConfigUpdate(ctx, in)
}

func (m *defaultNotifyManage) NotifyConfigIndex(ctx context.Context, in *NotifyConfigIndexReq, opts ...grpc.CallOption) (*NotifyConfigIndexResp, error) {
	client := sys.NewNotifyManageClient(m.cli.Conn())
	return client.NotifyConfigIndex(ctx, in, opts...)
}

func (d *directNotifyManage) NotifyConfigIndex(ctx context.Context, in *NotifyConfigIndexReq, opts ...grpc.CallOption) (*NotifyConfigIndexResp, error) {
	return d.svr.NotifyConfigIndex(ctx, in)
}

func (m *defaultNotifyManage) NotifyConfigDelete(ctx context.Context, in *WithID, opts ...grpc.CallOption) (*Empty, error) {
	client := sys.NewNotifyManageClient(m.cli.Conn())
	return client.NotifyConfigDelete(ctx, in, opts...)
}

func (d *directNotifyManage) NotifyConfigDelete(ctx context.Context, in *WithID, opts ...grpc.CallOption) (*Empty, error) {
	return d.svr.NotifyConfigDelete(ctx, in)
}

func (m *defaultNotifyManage) NotifyConfigSend(ctx context.Context, in *NotifyConfigSendReq, opts ...grpc.CallOption) (*Empty, error) {
	client := sys.NewNotifyManageClient(m.cli.Conn())
	return client.NotifyConfigSend(ctx, in, opts...)
}

func (d *directNotifyManage) NotifyConfigSend(ctx context.Context, in *NotifyConfigSendReq, opts ...grpc.CallOption) (*Empty, error) {
	return d.svr.NotifyConfigSend(ctx, in)
}

// 通知模版
func (m *defaultNotifyManage) NotifyTemplateRead(ctx context.Context, in *WithID, opts ...grpc.CallOption) (*NotifyTemplate, error) {
	client := sys.NewNotifyManageClient(m.cli.Conn())
	return client.NotifyTemplateRead(ctx, in, opts...)
}

// 通知模版
func (d *directNotifyManage) NotifyTemplateRead(ctx context.Context, in *WithID, opts ...grpc.CallOption) (*NotifyTemplate, error) {
	return d.svr.NotifyTemplateRead(ctx, in)
}

func (m *defaultNotifyManage) NotifyTemplateCreate(ctx context.Context, in *NotifyTemplate, opts ...grpc.CallOption) (*WithID, error) {
	client := sys.NewNotifyManageClient(m.cli.Conn())
	return client.NotifyTemplateCreate(ctx, in, opts...)
}

func (d *directNotifyManage) NotifyTemplateCreate(ctx context.Context, in *NotifyTemplate, opts ...grpc.CallOption) (*WithID, error) {
	return d.svr.NotifyTemplateCreate(ctx, in)
}

func (m *defaultNotifyManage) NotifyTemplateUpdate(ctx context.Context, in *NotifyTemplate, opts ...grpc.CallOption) (*Empty, error) {
	client := sys.NewNotifyManageClient(m.cli.Conn())
	return client.NotifyTemplateUpdate(ctx, in, opts...)
}

func (d *directNotifyManage) NotifyTemplateUpdate(ctx context.Context, in *NotifyTemplate, opts ...grpc.CallOption) (*Empty, error) {
	return d.svr.NotifyTemplateUpdate(ctx, in)
}

func (m *defaultNotifyManage) NotifyTemplateIndex(ctx context.Context, in *NotifyTemplateIndexReq, opts ...grpc.CallOption) (*NotifyTemplateIndexResp, error) {
	client := sys.NewNotifyManageClient(m.cli.Conn())
	return client.NotifyTemplateIndex(ctx, in, opts...)
}

func (d *directNotifyManage) NotifyTemplateIndex(ctx context.Context, in *NotifyTemplateIndexReq, opts ...grpc.CallOption) (*NotifyTemplateIndexResp, error) {
	return d.svr.NotifyTemplateIndex(ctx, in)
}

func (m *defaultNotifyManage) NotifyTemplateDelete(ctx context.Context, in *WithID, opts ...grpc.CallOption) (*Empty, error) {
	client := sys.NewNotifyManageClient(m.cli.Conn())
	return client.NotifyTemplateDelete(ctx, in, opts...)
}

func (d *directNotifyManage) NotifyTemplateDelete(ctx context.Context, in *WithID, opts ...grpc.CallOption) (*Empty, error) {
	return d.svr.NotifyTemplateDelete(ctx, in)
}

// 租户通知配置
func (m *defaultNotifyManage) NotifyConfigTemplateUpdate(ctx context.Context, in *NotifyConfigTemplate, opts ...grpc.CallOption) (*Empty, error) {
	client := sys.NewNotifyManageClient(m.cli.Conn())
	return client.NotifyConfigTemplateUpdate(ctx, in, opts...)
}

// 租户通知配置
func (d *directNotifyManage) NotifyConfigTemplateUpdate(ctx context.Context, in *NotifyConfigTemplate, opts ...grpc.CallOption) (*Empty, error) {
	return d.svr.NotifyConfigTemplateUpdate(ctx, in)
}

func (m *defaultNotifyManage) NotifyConfigTemplateDelete(ctx context.Context, in *NotifyConfigTemplateDeleteReq, opts ...grpc.CallOption) (*Empty, error) {
	client := sys.NewNotifyManageClient(m.cli.Conn())
	return client.NotifyConfigTemplateDelete(ctx, in, opts...)
}

func (d *directNotifyManage) NotifyConfigTemplateDelete(ctx context.Context, in *NotifyConfigTemplateDeleteReq, opts ...grpc.CallOption) (*Empty, error) {
	return d.svr.NotifyConfigTemplateDelete(ctx, in)
}

func (m *defaultNotifyManage) NotifyConfigTemplateIndex(ctx context.Context, in *NotifyConfigTemplateIndexReq, opts ...grpc.CallOption) (*NotifyConfigTemplateIndexResp, error) {
	client := sys.NewNotifyManageClient(m.cli.Conn())
	return client.NotifyConfigTemplateIndex(ctx, in, opts...)
}

func (d *directNotifyManage) NotifyConfigTemplateIndex(ctx context.Context, in *NotifyConfigTemplateIndexReq, opts ...grpc.CallOption) (*NotifyConfigTemplateIndexResp, error) {
	return d.svr.NotifyConfigTemplateIndex(ctx, in)
}

func (m *defaultNotifyManage) NotifyChannelRead(ctx context.Context, in *WithID, opts ...grpc.CallOption) (*NotifyChannel, error) {
	client := sys.NewNotifyManageClient(m.cli.Conn())
	return client.NotifyChannelRead(ctx, in, opts...)
}

func (d *directNotifyManage) NotifyChannelRead(ctx context.Context, in *WithID, opts ...grpc.CallOption) (*NotifyChannel, error) {
	return d.svr.NotifyChannelRead(ctx, in)
}

func (m *defaultNotifyManage) NotifyChannelCreate(ctx context.Context, in *NotifyChannel, opts ...grpc.CallOption) (*WithID, error) {
	client := sys.NewNotifyManageClient(m.cli.Conn())
	return client.NotifyChannelCreate(ctx, in, opts...)
}

func (d *directNotifyManage) NotifyChannelCreate(ctx context.Context, in *NotifyChannel, opts ...grpc.CallOption) (*WithID, error) {
	return d.svr.NotifyChannelCreate(ctx, in)
}

func (m *defaultNotifyManage) NotifyChannelUpdate(ctx context.Context, in *NotifyChannel, opts ...grpc.CallOption) (*Empty, error) {
	client := sys.NewNotifyManageClient(m.cli.Conn())
	return client.NotifyChannelUpdate(ctx, in, opts...)
}

func (d *directNotifyManage) NotifyChannelUpdate(ctx context.Context, in *NotifyChannel, opts ...grpc.CallOption) (*Empty, error) {
	return d.svr.NotifyChannelUpdate(ctx, in)
}

func (m *defaultNotifyManage) NotifyChannelIndex(ctx context.Context, in *NotifyChannelIndexReq, opts ...grpc.CallOption) (*NotifyChannelIndexResp, error) {
	client := sys.NewNotifyManageClient(m.cli.Conn())
	return client.NotifyChannelIndex(ctx, in, opts...)
}

func (d *directNotifyManage) NotifyChannelIndex(ctx context.Context, in *NotifyChannelIndexReq, opts ...grpc.CallOption) (*NotifyChannelIndexResp, error) {
	return d.svr.NotifyChannelIndex(ctx, in)
}

func (m *defaultNotifyManage) NotifyChannelDelete(ctx context.Context, in *WithID, opts ...grpc.CallOption) (*Empty, error) {
	client := sys.NewNotifyManageClient(m.cli.Conn())
	return client.NotifyChannelDelete(ctx, in, opts...)
}

func (d *directNotifyManage) NotifyChannelDelete(ctx context.Context, in *WithID, opts ...grpc.CallOption) (*Empty, error) {
	return d.svr.NotifyChannelDelete(ctx, in)
}
