// Code generated by goctl. DO NOT EDIT.
// Source: sys.proto

package dictmanage

import (
	"context"

	"gitee.com/i-Things/core/service/syssvr/internal/svc"
	"gitee.com/i-Things/core/service/syssvr/pb/sys"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AccessInfo                 = sys.AccessInfo
	AccessInfoIndexReq         = sys.AccessInfoIndexReq
	AccessInfoIndexResp        = sys.AccessInfoIndexResp
	ApiInfo                    = sys.ApiInfo
	ApiInfoIndexReq            = sys.ApiInfoIndexReq
	ApiInfoIndexResp           = sys.ApiInfoIndexResp
	AppInfo                    = sys.AppInfo
	AppInfoIndexReq            = sys.AppInfoIndexReq
	AppInfoIndexResp           = sys.AppInfoIndexResp
	AppModuleIndexReq          = sys.AppModuleIndexReq
	AppModuleIndexResp         = sys.AppModuleIndexResp
	AppModuleMultiUpdateReq    = sys.AppModuleMultiUpdateReq
	AppPolicy                  = sys.AppPolicy
	AppPolicyReadReq           = sys.AppPolicyReadReq
	AreaInfo                   = sys.AreaInfo
	AreaInfoIndexReq           = sys.AreaInfoIndexReq
	AreaInfoIndexResp          = sys.AreaInfoIndexResp
	AreaInfoReadReq            = sys.AreaInfoReadReq
	AreaWithID                 = sys.AreaWithID
	AuthApiInfo                = sys.AuthApiInfo
	ConfigResp                 = sys.ConfigResp
	DataArea                   = sys.DataArea
	DataAreaIndexReq           = sys.DataAreaIndexReq
	DataAreaIndexResp          = sys.DataAreaIndexResp
	DataAreaMultiDeleteReq     = sys.DataAreaMultiDeleteReq
	DataAreaMultiUpdateReq     = sys.DataAreaMultiUpdateReq
	DataProject                = sys.DataProject
	DataProjectIndexReq        = sys.DataProjectIndexReq
	DataProjectIndexResp       = sys.DataProjectIndexResp
	DataProjectMultiUpdateReq  = sys.DataProjectMultiUpdateReq
	DateRange                  = sys.DateRange
	DictDetail                 = sys.DictDetail
	DictDetailIndexReq         = sys.DictDetailIndexReq
	DictDetailIndexResp        = sys.DictDetailIndexResp
	DictInfo                   = sys.DictInfo
	DictInfoIndexReq           = sys.DictInfoIndexReq
	DictInfoIndexResp          = sys.DictInfoIndexResp
	DictInfoReadReq            = sys.DictInfoReadReq
	Empty                      = sys.Empty
	IDList                     = sys.IDList
	JwtToken                   = sys.JwtToken
	LoginLogCreateReq          = sys.LoginLogCreateReq
	LoginLogIndexReq           = sys.LoginLogIndexReq
	LoginLogIndexResp          = sys.LoginLogIndexResp
	LoginLogInfo               = sys.LoginLogInfo
	Map                        = sys.Map
	MenuInfo                   = sys.MenuInfo
	MenuInfoIndexReq           = sys.MenuInfoIndexReq
	MenuInfoIndexResp          = sys.MenuInfoIndexResp
	MessageInfo                = sys.MessageInfo
	MessageInfoIndexReq        = sys.MessageInfoIndexReq
	MessageInfoIndexResp       = sys.MessageInfoIndexResp
	MessageInfoSendReq         = sys.MessageInfoSendReq
	ModuleInfo                 = sys.ModuleInfo
	ModuleInfoIndexReq         = sys.ModuleInfoIndexReq
	ModuleInfoIndexResp        = sys.ModuleInfoIndexResp
	NotifyInfo                 = sys.NotifyInfo
	NotifyInfoIndexReq         = sys.NotifyInfoIndexReq
	NotifyInfoIndexResp        = sys.NotifyInfoIndexResp
	NotifyInfoSendReq          = sys.NotifyInfoSendReq
	NotifyTemplate             = sys.NotifyTemplate
	NotifyTemplateIndexReq     = sys.NotifyTemplateIndexReq
	NotifyTemplateIndexResp    = sys.NotifyTemplateIndexResp
	OperLogCreateReq           = sys.OperLogCreateReq
	OperLogIndexReq            = sys.OperLogIndexReq
	OperLogIndexResp           = sys.OperLogIndexResp
	OperLogInfo                = sys.OperLogInfo
	OpsFeedback                = sys.OpsFeedback
	OpsFeedbackIndexReq        = sys.OpsFeedbackIndexReq
	OpsFeedbackIndexResp       = sys.OpsFeedbackIndexResp
	OpsWorkOrder               = sys.OpsWorkOrder
	OpsWorkOrderIndexReq       = sys.OpsWorkOrderIndexReq
	OpsWorkOrderIndexResp      = sys.OpsWorkOrderIndexResp
	PageInfo                   = sys.PageInfo
	PageInfo_OrderBy           = sys.PageInfo_OrderBy
	Point                      = sys.Point
	ProjectInfo                = sys.ProjectInfo
	ProjectInfoIndexReq        = sys.ProjectInfoIndexReq
	ProjectInfoIndexResp       = sys.ProjectInfoIndexResp
	ProjectWithID              = sys.ProjectWithID
	RoleAccessIndexReq         = sys.RoleAccessIndexReq
	RoleAccessIndexResp        = sys.RoleAccessIndexResp
	RoleAccessMultiUpdateReq   = sys.RoleAccessMultiUpdateReq
	RoleApiAuthReq             = sys.RoleApiAuthReq
	RoleAppIndexReq            = sys.RoleAppIndexReq
	RoleAppIndexResp           = sys.RoleAppIndexResp
	RoleAppMultiUpdateReq      = sys.RoleAppMultiUpdateReq
	RoleAppUpdateReq           = sys.RoleAppUpdateReq
	RoleInfo                   = sys.RoleInfo
	RoleInfoIndexReq           = sys.RoleInfoIndexReq
	RoleInfoIndexResp          = sys.RoleInfoIndexResp
	RoleMenuIndexReq           = sys.RoleMenuIndexReq
	RoleMenuIndexResp          = sys.RoleMenuIndexResp
	RoleMenuMultiUpdateReq     = sys.RoleMenuMultiUpdateReq
	RoleModuleIndexReq         = sys.RoleModuleIndexReq
	RoleModuleIndexResp        = sys.RoleModuleIndexResp
	RoleModuleMultiUpdateReq   = sys.RoleModuleMultiUpdateReq
	TenantAccessIndexReq       = sys.TenantAccessIndexReq
	TenantAccessIndexResp      = sys.TenantAccessIndexResp
	TenantAccessMultiUpdateReq = sys.TenantAccessMultiUpdateReq
	TenantAppCreateReq         = sys.TenantAppCreateReq
	TenantAppIndexReq          = sys.TenantAppIndexReq
	TenantAppIndexResp         = sys.TenantAppIndexResp
	TenantAppMenu              = sys.TenantAppMenu
	TenantAppMenuIndexReq      = sys.TenantAppMenuIndexReq
	TenantAppMenuIndexResp     = sys.TenantAppMenuIndexResp
	TenantAppModule            = sys.TenantAppModule
	TenantAppMultiUpdateReq    = sys.TenantAppMultiUpdateReq
	TenantAppWithIDOrCode      = sys.TenantAppWithIDOrCode
	TenantInfo                 = sys.TenantInfo
	TenantInfoCreateReq        = sys.TenantInfoCreateReq
	TenantInfoIndexReq         = sys.TenantInfoIndexReq
	TenantInfoIndexResp        = sys.TenantInfoIndexResp
	TenantModuleCreateReq      = sys.TenantModuleCreateReq
	TenantModuleIndexReq       = sys.TenantModuleIndexReq
	TenantModuleIndexResp      = sys.TenantModuleIndexResp
	TenantModuleWithIDOrCode   = sys.TenantModuleWithIDOrCode
	TenantNotify               = sys.TenantNotify
	TenantNotifyIndexReq       = sys.TenantNotifyIndexReq
	TenantNotifyIndexResp      = sys.TenantNotifyIndexResp
	TenantNotifyMultiUpdateReq = sys.TenantNotifyMultiUpdateReq
	TenantOpenCheckTokenReq    = sys.TenantOpenCheckTokenReq
	TenantOpenCheckTokenResp   = sys.TenantOpenCheckTokenResp
	TenantOpenWebHook          = sys.TenantOpenWebHook
	UserAreaApplyCreateReq     = sys.UserAreaApplyCreateReq
	UserAreaApplyDealReq       = sys.UserAreaApplyDealReq
	UserAreaApplyIndexReq      = sys.UserAreaApplyIndexReq
	UserAreaApplyIndexResp     = sys.UserAreaApplyIndexResp
	UserAreaApplyInfo          = sys.UserAreaApplyInfo
	UserCaptchaReq             = sys.UserCaptchaReq
	UserCaptchaResp            = sys.UserCaptchaResp
	UserChangePwdReq           = sys.UserChangePwdReq
	UserCheckTokenReq          = sys.UserCheckTokenReq
	UserCheckTokenResp         = sys.UserCheckTokenResp
	UserCreateResp             = sys.UserCreateResp
	UserForgetPwdReq           = sys.UserForgetPwdReq
	UserInfo                   = sys.UserInfo
	UserInfoCreateReq          = sys.UserInfoCreateReq
	UserInfoDeleteReq          = sys.UserInfoDeleteReq
	UserInfoIndexReq           = sys.UserInfoIndexReq
	UserInfoIndexResp          = sys.UserInfoIndexResp
	UserInfoReadReq            = sys.UserInfoReadReq
	UserInfoUpdateReq          = sys.UserInfoUpdateReq
	UserLoginReq               = sys.UserLoginReq
	UserLoginResp              = sys.UserLoginResp
	UserMessage                = sys.UserMessage
	UserMessageIndexReq        = sys.UserMessageIndexReq
	UserMessageIndexResp       = sys.UserMessageIndexResp
	UserMessageStatistics      = sys.UserMessageStatistics
	UserMessageStatisticsResp  = sys.UserMessageStatisticsResp
	UserProfile                = sys.UserProfile
	UserProfileIndexReq        = sys.UserProfileIndexReq
	UserProfileIndexResp       = sys.UserProfileIndexResp
	UserRegisterReq            = sys.UserRegisterReq
	UserRegisterResp           = sys.UserRegisterResp
	UserRoleIndexReq           = sys.UserRoleIndexReq
	UserRoleIndexResp          = sys.UserRoleIndexResp
	UserRoleMultiUpdateReq     = sys.UserRoleMultiUpdateReq
	WithAppCodeID              = sys.WithAppCodeID
	WithCode                   = sys.WithCode
	WithID                     = sys.WithID
	WithIDCode                 = sys.WithIDCode

	DictManage interface {
		DictInfoCreate(ctx context.Context, in *DictInfo, opts ...grpc.CallOption) (*WithID, error)
		DictInfoIndex(ctx context.Context, in *DictInfoIndexReq, opts ...grpc.CallOption) (*DictInfoIndexResp, error)
		DictInfoUpdate(ctx context.Context, in *DictInfo, opts ...grpc.CallOption) (*Empty, error)
		DictInfoDelete(ctx context.Context, in *WithID, opts ...grpc.CallOption) (*Empty, error)
		DictInfoRead(ctx context.Context, in *DictInfoReadReq, opts ...grpc.CallOption) (*DictInfo, error)
		DictDetailCreate(ctx context.Context, in *DictDetail, opts ...grpc.CallOption) (*WithID, error)
		DictDetailIndex(ctx context.Context, in *DictDetailIndexReq, opts ...grpc.CallOption) (*DictDetailIndexResp, error)
		DictDetailUpdate(ctx context.Context, in *DictDetail, opts ...grpc.CallOption) (*Empty, error)
		DictDetailDelete(ctx context.Context, in *WithID, opts ...grpc.CallOption) (*Empty, error)
	}

	defaultDictManage struct {
		cli zrpc.Client
	}

	directDictManage struct {
		svcCtx *svc.ServiceContext
		svr    sys.DictManageServer
	}
)

func NewDictManage(cli zrpc.Client) DictManage {
	return &defaultDictManage{
		cli: cli,
	}
}

func NewDirectDictManage(svcCtx *svc.ServiceContext, svr sys.DictManageServer) DictManage {
	return &directDictManage{
		svr:    svr,
		svcCtx: svcCtx,
	}
}

func (m *defaultDictManage) DictInfoCreate(ctx context.Context, in *DictInfo, opts ...grpc.CallOption) (*WithID, error) {
	client := sys.NewDictManageClient(m.cli.Conn())
	return client.DictInfoCreate(ctx, in, opts...)
}

func (d *directDictManage) DictInfoCreate(ctx context.Context, in *DictInfo, opts ...grpc.CallOption) (*WithID, error) {
	return d.svr.DictInfoCreate(ctx, in)
}

func (m *defaultDictManage) DictInfoIndex(ctx context.Context, in *DictInfoIndexReq, opts ...grpc.CallOption) (*DictInfoIndexResp, error) {
	client := sys.NewDictManageClient(m.cli.Conn())
	return client.DictInfoIndex(ctx, in, opts...)
}

func (d *directDictManage) DictInfoIndex(ctx context.Context, in *DictInfoIndexReq, opts ...grpc.CallOption) (*DictInfoIndexResp, error) {
	return d.svr.DictInfoIndex(ctx, in)
}

func (m *defaultDictManage) DictInfoUpdate(ctx context.Context, in *DictInfo, opts ...grpc.CallOption) (*Empty, error) {
	client := sys.NewDictManageClient(m.cli.Conn())
	return client.DictInfoUpdate(ctx, in, opts...)
}

func (d *directDictManage) DictInfoUpdate(ctx context.Context, in *DictInfo, opts ...grpc.CallOption) (*Empty, error) {
	return d.svr.DictInfoUpdate(ctx, in)
}

func (m *defaultDictManage) DictInfoDelete(ctx context.Context, in *WithID, opts ...grpc.CallOption) (*Empty, error) {
	client := sys.NewDictManageClient(m.cli.Conn())
	return client.DictInfoDelete(ctx, in, opts...)
}

func (d *directDictManage) DictInfoDelete(ctx context.Context, in *WithID, opts ...grpc.CallOption) (*Empty, error) {
	return d.svr.DictInfoDelete(ctx, in)
}

func (m *defaultDictManage) DictInfoRead(ctx context.Context, in *DictInfoReadReq, opts ...grpc.CallOption) (*DictInfo, error) {
	client := sys.NewDictManageClient(m.cli.Conn())
	return client.DictInfoRead(ctx, in, opts...)
}

func (d *directDictManage) DictInfoRead(ctx context.Context, in *DictInfoReadReq, opts ...grpc.CallOption) (*DictInfo, error) {
	return d.svr.DictInfoRead(ctx, in)
}

func (m *defaultDictManage) DictDetailCreate(ctx context.Context, in *DictDetail, opts ...grpc.CallOption) (*WithID, error) {
	client := sys.NewDictManageClient(m.cli.Conn())
	return client.DictDetailCreate(ctx, in, opts...)
}

func (d *directDictManage) DictDetailCreate(ctx context.Context, in *DictDetail, opts ...grpc.CallOption) (*WithID, error) {
	return d.svr.DictDetailCreate(ctx, in)
}

func (m *defaultDictManage) DictDetailIndex(ctx context.Context, in *DictDetailIndexReq, opts ...grpc.CallOption) (*DictDetailIndexResp, error) {
	client := sys.NewDictManageClient(m.cli.Conn())
	return client.DictDetailIndex(ctx, in, opts...)
}

func (d *directDictManage) DictDetailIndex(ctx context.Context, in *DictDetailIndexReq, opts ...grpc.CallOption) (*DictDetailIndexResp, error) {
	return d.svr.DictDetailIndex(ctx, in)
}

func (m *defaultDictManage) DictDetailUpdate(ctx context.Context, in *DictDetail, opts ...grpc.CallOption) (*Empty, error) {
	client := sys.NewDictManageClient(m.cli.Conn())
	return client.DictDetailUpdate(ctx, in, opts...)
}

func (d *directDictManage) DictDetailUpdate(ctx context.Context, in *DictDetail, opts ...grpc.CallOption) (*Empty, error) {
	return d.svr.DictDetailUpdate(ctx, in)
}

func (m *defaultDictManage) DictDetailDelete(ctx context.Context, in *WithID, opts ...grpc.CallOption) (*Empty, error) {
	client := sys.NewDictManageClient(m.cli.Conn())
	return client.DictDetailDelete(ctx, in, opts...)
}

func (d *directDictManage) DictDetailDelete(ctx context.Context, in *WithID, opts ...grpc.CallOption) (*Empty, error) {
	return d.svr.DictDetailDelete(ctx, in)
}
