// Code generated by goctl. DO NOT EDIT.
// Source: sys.proto

package server

import (
	"context"

	"gitee.com/i-Things/core/service/syssvr/internal/logic/notifymanage"
	"gitee.com/i-Things/core/service/syssvr/internal/svc"
	"gitee.com/i-Things/core/service/syssvr/pb/sys"
)

type NotifyManageServer struct {
	svcCtx *svc.ServiceContext
	sys.UnimplementedNotifyManageServer
}

func NewNotifyManageServer(svcCtx *svc.ServiceContext) *NotifyManageServer {
	return &NotifyManageServer{
		svcCtx: svcCtx,
	}
}

// 站内信
func (s *NotifyManageServer) MessageInfoSend(ctx context.Context, in *sys.MessageInfoSendReq) (*sys.WithID, error) {
	l := notifymanagelogic.NewMessageInfoSendLogic(ctx, s.svcCtx)
	return l.MessageInfoSend(in)
}

func (s *NotifyManageServer) MessageInfoIndex(ctx context.Context, in *sys.MessageInfoIndexReq) (*sys.MessageInfoIndexResp, error) {
	l := notifymanagelogic.NewMessageInfoIndexLogic(ctx, s.svcCtx)
	return l.MessageInfoIndex(in)
}

func (s *NotifyManageServer) MessageInfoUpdate(ctx context.Context, in *sys.MessageInfo) (*sys.Empty, error) {
	l := notifymanagelogic.NewMessageInfoUpdateLogic(ctx, s.svcCtx)
	return l.MessageInfoUpdate(in)
}

func (s *NotifyManageServer) MessageInfoDelete(ctx context.Context, in *sys.WithID) (*sys.Empty, error) {
	l := notifymanagelogic.NewMessageInfoDeleteLogic(ctx, s.svcCtx)
	return l.MessageInfoDelete(in)
}

// 通知配置信息
func (s *NotifyManageServer) NotifyInfoRead(ctx context.Context, in *sys.WithIDCode) (*sys.NotifyInfo, error) {
	l := notifymanagelogic.NewNotifyInfoReadLogic(ctx, s.svcCtx)
	return l.NotifyInfoRead(in)
}

func (s *NotifyManageServer) NotifyInfoCreate(ctx context.Context, in *sys.NotifyInfo) (*sys.WithID, error) {
	l := notifymanagelogic.NewNotifyInfoCreateLogic(ctx, s.svcCtx)
	return l.NotifyInfoCreate(in)
}

func (s *NotifyManageServer) NotifyInfoUpdate(ctx context.Context, in *sys.NotifyInfo) (*sys.Empty, error) {
	l := notifymanagelogic.NewNotifyInfoUpdateLogic(ctx, s.svcCtx)
	return l.NotifyInfoUpdate(in)
}

func (s *NotifyManageServer) NotifyInfoIndex(ctx context.Context, in *sys.NotifyInfoIndexReq) (*sys.NotifyInfoIndexResp, error) {
	l := notifymanagelogic.NewNotifyInfoIndexLogic(ctx, s.svcCtx)
	return l.NotifyInfoIndex(in)
}

func (s *NotifyManageServer) NotifyInfoDelete(ctx context.Context, in *sys.WithID) (*sys.Empty, error) {
	l := notifymanagelogic.NewNotifyInfoDeleteLogic(ctx, s.svcCtx)
	return l.NotifyInfoDelete(in)
}

func (s *NotifyManageServer) NotifyInfoSend(ctx context.Context, in *sys.NotifyInfoSendReq) (*sys.Empty, error) {
	l := notifymanagelogic.NewNotifyInfoSendLogic(ctx, s.svcCtx)
	return l.NotifyInfoSend(in)
}

// 通知模版
func (s *NotifyManageServer) NotifyTemplateRead(ctx context.Context, in *sys.WithID) (*sys.NotifyTemplate, error) {
	l := notifymanagelogic.NewNotifyTemplateReadLogic(ctx, s.svcCtx)
	return l.NotifyTemplateRead(in)
}

func (s *NotifyManageServer) NotifyTemplateCreate(ctx context.Context, in *sys.NotifyTemplate) (*sys.WithID, error) {
	l := notifymanagelogic.NewNotifyTemplateCreateLogic(ctx, s.svcCtx)
	return l.NotifyTemplateCreate(in)
}

func (s *NotifyManageServer) NotifyTemplateUpdate(ctx context.Context, in *sys.NotifyTemplate) (*sys.Empty, error) {
	l := notifymanagelogic.NewNotifyTemplateUpdateLogic(ctx, s.svcCtx)
	return l.NotifyTemplateUpdate(in)
}

func (s *NotifyManageServer) NotifyTemplateIndex(ctx context.Context, in *sys.NotifyTemplateIndexReq) (*sys.NotifyTemplateIndexResp, error) {
	l := notifymanagelogic.NewNotifyTemplateIndexLogic(ctx, s.svcCtx)
	return l.NotifyTemplateIndex(in)
}

func (s *NotifyManageServer) NotifyTemplateDelete(ctx context.Context, in *sys.WithID) (*sys.Empty, error) {
	l := notifymanagelogic.NewNotifyTemplateDeleteLogic(ctx, s.svcCtx)
	return l.NotifyTemplateDelete(in)
}
